### PR TITLE
Add previous posts

### PR DESCRIPTION
**Pull request by ellisvalentiner**

### CODE REVIEW

**Review by ClaytonJY — APPROVED** [review]
huh, it just works that easily? cool.

**Comment by ellisvalentiner** [comment]
this actually doesn't include some of our most recent meetups

**Comment by ClaytonJY** [comment]
aaaand it looks like the formatting is broken and none of the links work :(

**Comment by ClaytonJY** [comment]
well, broken in the previews

**Comment by ellisvalentiner** [comment]
what do you mean?

**Comment by ClaytonJY** [comment]
On the main page of the netlify deployment, links in the posts don't work. The summarizing also removes all line breaks, so they're pretty rough looking

**Comment by ellisvalentiner** [comment]
I see what you mean now. [Here](https://github.com/ribice/kiss/blob/ba36599219664afa8669f9bfc105a3984b979558/layouts/index.html#L16) is where the magic happens. `.Summary` renders the content as plain text. However if you specify the split automatically with `<!--more-->` (even at the end of the document) then it will render Markdown. Make a new issue?

**Pull request merged**
